In [2]:
import os

os.listdir("./Images")

['IMG_9726.jpg',
 'IMG_9727.jpg',
 'IMG_9728.jpg',
 'IMG_9729.jpg',
 'IMG_9730.jpg',
 'IMG_9731.jpg',
 'IMG_9732.jpg',
 'IMG_9733.jpg',
 'IMG_9734.jpg',
 'IMG_9736.jpg']

In [13]:
import cv2

img = cv2.imread("./Images/IMG_9736.jpg")
img.shape

(3024, 4032, 3)

In [2]:
import os
import cv2
import numpy as np

images = os.listdir("./Images")

checker = (5, 6)  # (rows, columns)
criteria = (
    cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER,
    30,
    0.001,
)  # termination criteria
objpoints = []
imgpoints = []

objp = np.zeros((1, checker[0] * checker[1], 3), np.float32)  # 3D points
objp[0, :, :2] = np.mgrid[0 : checker[0], 0 : checker[1]].T.reshape(-1, 2)

for i in range(len(images)):
    img = cv2.imread("./Images/" + images[i])
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCorners(gray, checker, None)  # find corners
    if ret:
        objpoints.append(objp)
        corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
        imgpoints.append(corners2)
        img = cv2.drawChessboardCorners(img, checker, corners2, ret)
        cv2.namedWindow("image" + str(i), cv2.WINDOW_NORMAL)
        cv2.resizeWindow("image" + str(i), 800, 600)
        cv2.imshow("image" + str(i), img)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Calibration
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(
    objpoints, imgpoints, gray.shape[::-1], None, None
)


In [3]:
ret

1.7461936272520837

In [4]:
mtx

array([[3.28261164e+03, 0.00000000e+00, 2.02403056e+03],
       [0.00000000e+00, 3.28885353e+03, 1.45308413e+03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [5]:
dist

array([[ 2.87579407e-01, -1.52709073e+00, -6.24107384e-03,
         2.07482576e-03,  2.37278047e+00]])

In [7]:
rvecs

(array([[-0.00888653],
        [-0.06024753],
        [-1.58140871]]),
 array([[-0.41618971],
        [ 0.33138209],
        [-1.59353817]]),
 array([[-0.02663447],
        [ 0.58502891],
        [-1.34324473]]),
 array([[ 0.45208187],
        [ 0.43119736],
        [-1.48820138]]),
 array([[ 0.67303598],
        [-0.18746837],
        [-1.18617878]]),
 array([[ 0.43494683],
        [-0.59004422],
        [-1.45430323]]),
 array([[-0.19887921],
        [-0.70318325],
        [-1.38833249]]),
 array([[-0.52690737],
        [-0.5878565 ],
        [-1.44397516]]),
 array([[-0.74796833],
        [-0.05533612],
        [-1.63210284]]),
 array([[-0.75513286],
        [-0.80388963],
        [-1.45532522]]))

In [8]:
tvecs

(array([[-2.14112772],
        [ 2.76476017],
        [14.39944326]]),
 array([[-2.02351307],
        [ 2.74080965],
        [13.9465859 ]]),
 array([[-4.0319099 ],
        [ 2.45320743],
        [14.95647305]]),
 array([[-2.41338223],
        [ 3.03255059],
        [13.40904107]]),
 array([[-2.83069116],
        [ 2.89173312],
        [11.56103764]]),
 array([[-0.7050961 ],
        [ 2.31830289],
        [12.19947839]]),
 array([[-0.48553632],
        [ 1.59285738],
        [11.47892757]]),
 array([[-2.46372369],
        [ 1.48497491],
        [11.73454195]]),
 array([[-2.90682818],
        [ 2.66973583],
        [13.37969217]]),
 array([[-2.5354837 ],
        [ 0.48231802],
        [ 7.69380429]]))

In [11]:
3.28261164e+03 * 1.22e-6

0.0040047862008

In [9]:
3.28885353e+03 * 1.22e-6

0.004012401306599999